server:
  port: 8761
spring:
  application:
    name: common-eureka
eureka:
  instance:
    hostname: 47.99.63.139
  client:
    serviceUrl:
      defaultZone: http://47.99.63.139:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
    response-cache-update-interval-ms: 3000
    response-cache-auto-expiration-in-seconds: 180