spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  instance:
    hostname: docker.for.mac.host.internal
  client:
    serviceUrl:
      defaultZone: http://docker.for.mac.host.internal:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false